<div class="titulo">
	<br/>Bienvenido<br/><br/>
	<div id="botones">
		<?php if($log){ ?>
		<a href="/?cat=home"><img src="/views/images/01.jpg"></a>
		<a href="/?cat=abmcategorias"><img src="/views/images/02.jpg"></a>
		<a href="/?cat=abmsubcategorias"><img src="/views/images/03.jpg"></a>
		<a href="/?cat=abmproductos"><img src="/views/images/04.jpg"></a>
		<a href="/?cat=abmnotas"><img src="/views/images/05.jpg"></a>
		<a href="/?cat=abmdestacados"><img src="/views/images/06.jpg"></a>
	
		<?php } ?>
	</div>
	

</div>