<div class="columna">
	<?php if(isset($pro[0])){ ?>
	<a href="/?cat=nota&id=<?php echo $pro[0]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[0]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[0]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[0]->texto;?></span>
			<span class="texto"><?php echo $pro[0]->fecha;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	
	<?php if(isset($pro[2])){ ?>
	<a href="/?cat=nota&id=<?php echo $pro[2]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[2]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[2]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[2]->texto;?></span>
			<span class="texto"><?php echo $pro[2]->fecha;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[4])){ ?>
	<a href="/?cat=nota&id=<?php echo $pro[4]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[4]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[4]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[4]->texto;?></span>
			<span class="texto"><?php echo $pro[4]->fecha;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[6])){ ?>
		<a href="/?cat=nota&id=<?php echo $pro[6]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[6]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[6]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[6]->texto;?></span>
		</div><span class="texto"><?php echo $pro[6]->fecha;?></span>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[8])){ ?>
		<a href="/?cat=nota&id=<?php echo $pro[8]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[8]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[8]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[8]->texto;?></span>
			<span class="texto"><?php echo $pro[8]->fecha;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
</div>
<div class="columna">
<?php if(isset($pro[1])){ ?>
	<a href="/?cat=nota&id=<?php echo $pro[1]->id; ?>"/>
	
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[1]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[1]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[1]->texto;?></span>
			<span class="texto"><?php echo $pro[1]->fecha;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	
	<?php if(isset($pro[3])){ ?>
		<a href="/?cat=nota&id=<?php echo $pro[3]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[3]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[3]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[3]->texto;?></span>
			<span class="texto"><?php echo $pro[3]->fecha;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[5])){ ?>
		<a href="/?cat=nota&id=<?php echo $pro[5]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[5]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[5]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[5]->texto;?></span>
			<span class="texto"><?php echo $pro[5]->fecha;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[7])){ ?>
		<a href="/?cat=nota&id=<?php echo $pro[7]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[7]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[7]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[7]->texto;?></span>
			<span class="texto"><?php echo $pro[7]->fecha;?></span>
		</div>
	</div>
	<?php } ?>
	
	<?php if(isset($pro[9])){ ?>
		<a href="/?cat=nota&id=<?php echo $pro[9]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[9]->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[9]->titulo; ?></span><br/>
			<span class="texto"><?php echo $pro[9]->texto;?></span>
			<span class="texto"><?php echo $pro[9]->fecha;?></span>
		</div>
	</div>
	<?php } ?>
</div>