<div class="columna">
	<?php if(isset($pro[0])){ ?>
	<a href="/?cat=producto&id=<?php echo $pro[0]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[0]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[0]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[0]->descripcion->texto;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	
	<?php if(isset($pro[2])){ ?>
	<a href="/?cat=producto&id=<?php echo $pro[2]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[2]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[2]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[2]->descripcion->texto;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[4])){ ?>
	<a href="/?cat=producto&id=<?php echo $pro[4]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[4]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[4]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[4]->descripcion->texto;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[6])){ ?>
		<a href="/?cat=producto&id=<?php echo $pro[6]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[6]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[6]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[6]->descripcion->texto;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[8])){ ?>
		<a href="/?cat=producto&id=<?php echo $pro[8]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[8]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[8]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[8]->descripcion->texto;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
</div>
<div class="columna">
	<?php if(isset($pro[1])){ ?>
	<a href="/?cat=producto&id=<?php echo $pro[1]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[1]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[1]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[1]->descripcion->texto;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	
	<?php if(isset($pro[3])){ ?>
		<a href="/?cat=producto&id=<?php echo $pro[3]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[3]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[3]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[3]->descripcion->texto;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[5])){ ?>
		<a href="/?cat=producto&id=<?php echo $pro[5]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[5]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[5]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[5]->descripcion->texto;?></span>
		</div>
	</div>
	</a>
	<?php } ?>
	
	<?php if(isset($pro[7])){ ?>
		<a href="/?cat=producto&id=<?php echo $pro[7]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[7]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[7]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[7]->descripcion->texto;?></span>
		</div>
	</div>
	<?php } ?>
	
	<?php if(isset($pro[9])){ ?>
		<a href="/?cat=producto&id=<?php echo $pro[9]->id; ?>"/>
	<div class="producto">
		<div class="foto">
		<img src="<?php echo $pro[9]->descripcion->foto->url; ?>" height="80px" width="80px" />
		</div>
		<div class="descript">
			<span class="titulo"><?php echo $pro[9]->nombre; ?></span><br/>
			<span class="texto"><?php echo $pro[9]->descripcion->texto;?></span>
		</div>
	</div>
	<?php } ?>
</div>